version: '3.7'

services:
  mysql:
    image: mysql:8.1
    restart: always
    container_name: database
    env_file:
      - .env.local
    volumes:
      - local_mytasks_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mytasks
    healthcheck:
      test: ["CMD", "mysql", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "--execute", "SHOW DATABASES;"]
      interval: 2s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: local.Dockerfile
    env_file:
      - .env.local
    networks:
      - mytasks
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql:mysql
    volumes:
      - ./backend:/app
      - .env.local:/app/.env.local
    entrypoint:
      [
        "npm",
        "run",
        "migrate:dev",
      ]

  frontend:
    build:
      context: ./frontend
      dockerfile: local.Dockerfile
    env_file:
      - .env.local
    networks:
      - mytasks
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - .env.local:/app/.env.local
    entrypoint:
      [
        "npm",
        "run",
        "dev",
      ]

networks:
  mytasks:
    driver: bridge

volumes:
  local_mytasks_data:
    external: true